-- =========================================================
-- DATABASE SCHEMA: SERENA RAGA (HOME MASSAGE BOOKING SYSTEM)
-- Jalankan query ini di Supabase SQL Editor:
-- https://supabase.com/dashboard/project/jbnvxlwjffanqusfrhpk/sql
-- =========================================================

-- 1. Enable UUID Extension
create extension if not exists "uuid-ossp";

-- 2. Tabel Services (Katalog Layanan Pijat)
create table if not exists services (
    id bigint generated by default as identity primary key,
    name text not null,
    category text default 'Body Massage',
    description text,
    duration_minutes integer not null default 60,
    price numeric not null default 150000,
    image_url text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabel Therapists (Daftar & Manajemen Terapis Lengkap)
create table if not exists therapists (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text not null,
    gender text default 'Female', -- 'Female', 'Male'
    birth_date date,
    nik text, -- Nomor Induk Kependudukan (16 Digit KTP)
    ktp_photo_url text, -- Foto KTP Kualitas HD untuk Verifikasi
    domicile_address text, -- Alamat Domisili Lengkap Terapis
    emergency_contact_name text, -- Nama Kontak Darurat (Keluarga)
    emergency_contact_phone text, -- No HP Kontak Darurat
    specialties text,
    experience_years integer default 1,
    photo_url text, -- Foto Profil Seragam Terapis
    cv_url text, -- Dokumen CV / Resume (PDF / Gambar)
    certificate_url text, -- Sertifikat Kompetensi Pijat / BNSP
    rating numeric(2,1) default 5.0,
    status text default 'available', -- 'available', 'on_duty', 'off_duty', 'pending_verification'
    commission_rate numeric not null default 60, -- Persentase bagi hasil terapis (contoh: 60%)
    bank_name text default 'BCA', -- Nama Bank untuk Payroll
    bank_account_number text, -- Nomor Rekening
    bank_account_name text, -- Nama Pemilik Rekening
    coverage_areas text default 'Jakarta Selatan, Tangerang Selatan', -- Area Jangkauan Layanan
    joined_date date default current_date, -- Tanggal Mulai Bergabung
    notes text, -- Catatan Internal HR / Admin
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =========================================================
-- MIGRATION HELPER (Jalankan query ini jika tabel therapists sudah ada):
-- =========================================================
-- alter table therapists add column if not exists nik text;
-- alter table therapists add column if not exists ktp_photo_url text;
-- alter table therapists add column if not exists domicile_address text;
-- alter table therapists add column if not exists birth_date date;
-- alter table therapists add column if not exists emergency_contact_name text;
-- alter table therapists add column if not exists emergency_contact_phone text;
-- alter table therapists add column if not exists cv_url text;
-- alter table therapists add column if not exists certificate_url text;
-- alter table therapists add column if not exists bank_name text default 'BCA';
-- alter table therapists add column if not exists bank_account_number text;
-- alter table therapists add column if not exists bank_account_name text;
-- alter table therapists add column if not exists coverage_areas text default 'Jakarta Selatan';
-- alter table therapists add column if not exists joined_date date default current_date;
-- alter table therapists add column if not exists notes text;
-- alter table therapists add column if not exists commission_rate numeric default 60;
-- =========================================================

-- Setup Supabase Storage Buckets untuk Foto & Dokumen Terapis
insert into storage.buckets (id, name, public)
values 
    ('therapist-photos', 'therapist-photos', true),
    ('therapist-documents', 'therapist-documents', true)
on conflict (id) do update set public = true;

-- Storage RLS Policies
drop policy if exists "Allow public read on therapist photos" on storage.objects;
create policy "Allow public read on therapist photos" on storage.objects for select using (bucket_id in ('therapist-photos', 'therapist-documents'));

drop policy if exists "Allow authenticated and anon uploads to therapist storage" on storage.objects;
create policy "Allow authenticated and anon uploads to therapist storage" on storage.objects for insert with check (bucket_id in ('therapist-photos', 'therapist-documents'));

drop policy if exists "Allow delete and update on therapist storage" on storage.objects;
create policy "Allow delete and update on therapist storage" on storage.objects for all using (bucket_id in ('therapist-photos', 'therapist-documents'));

-- 4. Tabel Customers (Data Pelanggan)
create table if not exists customers (
    id bigint generated by default as identity primary key,
    full_name text not null,
    phone text not null,
    email text,
    address text not null,
    city_area text,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Tabel Bookings (Pemesanan Layanan Home Massage)
create table if not exists bookings (
    id bigint generated by default as identity primary key,
    customer_id bigint references customers(id) on delete cascade,
    service_id bigint references services(id) on delete set null,
    therapist_id bigint references therapists(id) on delete set null,
    booking_date date not null default current_date,
    booking_time text not null default '10:00',
    service_address text not null,
    total_price numeric not null default 150000,
    status text default 'pending', -- 'pending', 'confirmed', 'on_the_way', 'in_progress', 'completed', 'cancelled'
    payment_method text default 'cash', -- 'cash', 'bank_transfer', 'qris', 'credit_card'
    payment_status text default 'unpaid', -- 'unpaid', 'paid', 'refunded'
    special_requests text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Tabel Invoices (Nota & Checkout Pembayaran)
create table if not exists invoices (
    id bigint generated by default as identity primary key,
    invoice_number text unique not null,
    booking_id bigint references bookings(id) on delete set null,
    customer_id bigint references customers(id) on delete set null,
    customer_name text not null,
    customer_phone text not null,
    service_id bigint references services(id) on delete set null,
    service_name text not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name text,
    booking_date date,
    booking_time text,
    service_address text,
    subtotal numeric not null default 0,
    discount numeric default 0,
    transport_fee numeric default 0,
    total_amount numeric not null default 0,
    payment_method text default 'cash', -- 'cash', 'qris', 'bank_transfer'
    payment_status text default 'unpaid', -- 'unpaid', 'paid', 'refunded'
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Tabel Reviews (Ulasan & Rating Pelanggan)
create table if not exists reviews (
    id bigint generated by default as identity primary key,
    booking_id bigint references bookings(id) on delete cascade,
    invoice_id bigint references invoices(id) on delete set null,
    therapist_id bigint references therapists(id) on delete set null,
    customer_name text,
    rating integer not null check (rating >= 1 and rating <= 5),
    comment text,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Tabel Brand Settings (Pengaturan Brand & Kontak Global)
create table if not exists brand_settings (
    id integer primary key default 1 check (id = 1),
    brand_name text not null default 'Serena Raga',
    tagline text default 'Comfortable Home Massage & Spa',
    description text default 'Layanan terapis pijat dan spa profesional langsung ke rumah, hotel, dan apartemen Anda.',
    whatsapp_number text not null default '6281234567890',
    phone_number text default '+62 812-3456-7890',
    email text default 'support@serenaraga.com',
    website_url text default 'https://serenaraga.com',
    instagram_handle text default '@serenaraga',
    operational_hours text default '08:00 - 22:00 WIB (Setiap Hari)',
    service_areas text default 'Jakarta, Tangerang, Depok, Bekasi, & Sekitarnya',
    bank_name text default 'BCA (Bank Central Asia)',
    bank_account_number text default '8720-1928-33',
    bank_account_holder text default 'PT Serena Raga Indonesia',
    qris_image_url text default '',
    invoice_footer_note text default 'Terima kasih telah mempercayakan relaksasi Anda pada Serena Raga.',
    invoice_support_text text default 'Dokumen ini merupakan bukti transaksi resmi. Layanan pelanggan WhatsApp {whatsapp}.',
    wa_invoice_message_template text default 'Halo {customer_name},\n\nTerima kasih telah menggunakan layanan *{brand_name}* ({service_name}).\nBerikut adalah rincian nota & invoice resmi Anda:\n\n📄 *No. Invoice:* {invoice_number}\n💰 *Total Tagihan:* {total_amount}\n📅 *Jadwal:* {booking_date} jam {booking_time}\n💳 *Status:* {payment_status}\n\n🔗 *Lihat Nota Digital:* {invoice_url}\n\nJika ada pertanyaan, silakan hubungi kami via WhatsApp ini.',
    wa_booking_message_template text default 'Halo {customer_name},\n\nPesanan *{service_name}* di *{brand_name}* Anda telah dikonfirmasi!\n\n📅 *Tanggal:* {booking_date}\n⏰ *Jam:* {booking_time}\n📍 *Alamat:* {address}\n💆 *Terapis:* {therapist_name}\n\nMohon bersiap 10 menit sebelum waktu pelayanan.',
    wa_support_default_message text default 'Halo Customer Service {brand_name}, saya butuh bantuan mengenai layanan / nota saya.',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed default brand settings if empty
insert into brand_settings (id, brand_name, whatsapp_number)
values (1, 'Serena Raga', '6281234567890')
on conflict (id) do nothing;

-- 9. Tabel App Users (Manajemen Pengguna & Hak Akses Admin / Kasir)
create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    email text,
    full_name text not null,
    password_hash text not null,
    role text not null default 'cashier' check (role in ('admin', 'cashier', 'manager')),
    phone text,
    avatar_url text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pastikan semua kolom baru tersedia jika tabel sudah terlanjur dibuat sebelumnya
alter table app_users add column if not exists email text;
alter table app_users add column if not exists phone text;
alter table app_users add column if not exists avatar_url text;
alter table app_users add column if not exists is_active boolean default true;

-- Seed default Super Admin user if not exists
insert into app_users (username, email, full_name, password_hash, role)
values 
    ('admin@serenaraga', 'admin@serenaraga.com', 'Owner / Super Admin', 'Adminserena2026', 'admin'),
    ('admin@serenaraga.com', 'admin@serenaraga.com', 'Owner / Super Admin', 'Adminserena2026', 'admin')
on conflict (username) do update
set 
    password_hash = excluded.password_hash,
    role = 'admin',
    is_active = true;

-- 10. Enable Row Level Security (RLS)
alter table services enable row level security;
alter table therapists enable row level security;
alter table customers enable row level security;
alter table bookings enable row level security;
alter table reviews enable row level security;
alter table invoices enable row level security;
alter table brand_settings enable row level security;
alter table app_users enable row level security;

-- 11. Re-create Public Policies Safely (Drop if exists then create)
drop policy if exists "Allow anon full access on services" on services;
create policy "Allow anon full access on services" on services for all using (true) with check (true);

drop policy if exists "Allow anon full access on therapists" on therapists;
create policy "Allow anon full access on therapists" on therapists for all using (true) with check (true);

drop policy if exists "Allow anon full access on customers" on customers;
create policy "Allow anon full access on customers" on customers for all using (true) with check (true);

drop policy if exists "Allow anon full access on bookings" on bookings;
create policy "Allow anon full access on bookings" on bookings for all using (true) with check (true);

drop policy if exists "Allow anon full access on reviews" on reviews;
create policy "Allow anon full access on reviews" on reviews for all using (true) with check (true);

drop policy if exists "Allow anon full access on invoices" on invoices;
create policy "Allow anon full access on invoices" on invoices for all using (true) with check (true);

drop policy if exists "Allow anon full access on brand_settings" on brand_settings;
create policy "Allow anon full access on brand_settings" on brand_settings for all using (true) with check (true);

drop policy if exists "Allow anon full access on app_users" on app_users;
create policy "Allow anon full access on app_users" on app_users for all using (true) with check (true);

-- 12. Create Indexes for Performance
create index if not exists idx_bookings_customer on bookings(customer_id);
create index if not exists idx_bookings_service on bookings(service_id);
create index if not exists idx_bookings_therapist on bookings(therapist_id);
create index if not exists idx_bookings_date on bookings(booking_date);
create index if not exists idx_therapists_status on therapists(status);
create index if not exists idx_invoices_number on invoices(invoice_number);
create index if not exists idx_invoices_booking on invoices(booking_id);
create index if not exists idx_app_users_username on app_users(username);
create index if not exists idx_app_users_role on app_users(role);

-- 13. Storage Buckets & Policies for Therapist Photos & Documents
-- Membuat storage bucket otomatis jika belum ada
insert into storage.buckets (id, name, public)
values 
    ('therapist-photos', 'therapist-photos', true),
    ('therapist-documents', 'therapist-documents', true)
on conflict (id) do update set public = true;

-- Policy agar upload foto & dokumen terapis diizinkan tanpa error RLS
drop policy if exists "Public Access for Therapist Storage" on storage.objects;
create policy "Public Access for Therapist Storage"
on storage.objects for all
using (bucket_id in ('therapist-photos', 'therapist-documents'))
with check (bucket_id in ('therapist-photos', 'therapist-documents'));

-- 14. Tabel Therapist Payouts (Rekap Bagi Hasil & Slip Pembayaran Terapis)
create table if not exists therapist_payouts (
    id bigint generated by default as identity primary key,
    payout_number text unique not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name text not null,
    period_type text default 'monthly', -- 'daily', 'weekly', 'monthly', 'custom'
    period_start date not null,
    period_end date not null,
    total_bookings integer not null default 0,
    gross_amount numeric not null default 0,
    commission_rate numeric not null default 60,
    therapist_fee numeric not null default 0,
    company_fee numeric not null default 0,
    bonus_amount numeric default 0,
    deduction_amount numeric default 0,
    net_amount numeric not null default 0,
    bank_name text default 'BCA',
    bank_account_number text,
    bank_account_name text,
    payment_status text default 'paid', -- 'pending', 'paid'
    payment_date date default current_date,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table therapist_payouts enable row level security;
drop policy if exists "Allow anon full access on therapist_payouts" on therapist_payouts;
create policy "Allow anon full access on therapist_payouts" on therapist_payouts for all using (true) with check (true);

create index if not exists idx_payouts_therapist on therapist_payouts(therapist_id);
create index if not exists idx_payouts_number on therapist_payouts(payout_number);
create index if not exists idx_payouts_period on therapist_payouts(period_start, period_end);

