-- =========================================================
-- DATABASE SCHEMA: SERENA RAGA (HOME MASSAGE BOOKING SYSTEM)
-- Jalankan query ini di Supabase SQL Editor:
-- https://supabase.com/dashboard/project/jbnvxlwjffanqusfrhpk/sql
-- =========================================================

-- 1. Enable UUID Extension
create extension if not exists "uuid-ossp";

-- 2. Tabel Services (Katalog Layanan Pijat)
create table if not exists services (
    id bigint generated by default as identity primary key,
    name text not null,
    category text default 'Body Massage',
    description text,
    duration_minutes integer not null default 60,
    price numeric not null default 150000,
    image_url text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabel Therapists (Daftar & Manajemen Terapis Lengkap)
create table if not exists therapists (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text not null,
    gender text default 'Female', -- 'Female', 'Male'
    birth_date date,
    nik text, -- Nomor Induk Kependudukan (16 Digit KTP)
    ktp_photo_url text, -- Foto KTP Kualitas HD untuk Verifikasi
    domicile_address text, -- Alamat Domisili Lengkap Terapis
    emergency_contact_name text, -- Nama Kontak Darurat (Keluarga)
    emergency_contact_phone text, -- No HP Kontak Darurat
    specialties text,
    experience_years integer default 1,
    photo_url text, -- Foto Profil Seragam Terapis
    cv_url text, -- Dokumen CV / Resume (PDF / Gambar)
    certificate_url text, -- Sertifikat Kompetensi Pijat / BNSP
    rating numeric(2,1) default 5.0,
    status text default 'available', -- 'available', 'on_duty', 'off_duty', 'pending_verification'
    commission_rate numeric not null default 60, -- Persentase bagi hasil terapis (contoh: 60%)
    bank_name text default 'BCA', -- Nama Bank untuk Payroll
    bank_account_number text, -- Nomor Rekening
    bank_account_name text, -- Nama Pemilik Rekening
    coverage_areas text default 'Jakarta Selatan, Tangerang Selatan', -- Area Jangkauan Layanan
    joined_date date default current_date, -- Tanggal Mulai Bergabung
    notes text, -- Catatan Internal HR / Admin
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =========================================================
-- MIGRATION HELPER (Jalankan query ini jika tabel therapists sudah ada):
-- =========================================================
-- alter table therapists add column if not exists nik text;
-- alter table therapists add column if not exists ktp_photo_url text;
-- alter table therapists add column if not exists domicile_address text;
-- alter table therapists add column if not exists birth_date date;
-- alter table therapists add column if not exists emergency_contact_name text;
-- alter table therapists add column if not exists emergency_contact_phone text;
-- alter table therapists add column if not exists cv_url text;
-- alter table therapists add column if not exists certificate_url text;
-- alter table therapists add column if not exists bank_name text default 'BCA';
-- alter table therapists add column if not exists bank_account_number text;
-- alter table therapists add column if not exists bank_account_name text;
-- alter table therapists add column if not exists coverage_areas text default 'Jakarta Selatan';
-- alter table therapists add column if not exists joined_date date default current_date;
-- alter table therapists add column if not exists notes text;
-- alter table therapists add column if not exists commission_rate numeric default 60;
-- =========================================================

-- Setup Supabase Storage Buckets untuk Foto Terapis, Dokumen, & Brand Assets (QRIS/Logo)
insert into storage.buckets (id, name, public)
values 
    ('brand-assets', 'brand-assets', true),
    ('therapist-photos', 'therapist-photos', true),
    ('therapist-documents', 'therapist-documents', true)
on conflict (id) do update set public = true;

-- Storage RLS Policies
drop policy if exists "Allow public read on therapist photos" on storage.objects;
create policy "Allow public read on therapist photos" on storage.objects for select using (bucket_id in ('brand-assets', 'therapist-photos', 'therapist-documents'));

drop policy if exists "Allow authenticated and anon uploads to therapist storage" on storage.objects;
create policy "Allow authenticated and anon uploads to therapist storage" on storage.objects for insert with check (bucket_id in ('brand-assets', 'therapist-photos', 'therapist-documents'));

drop policy if exists "Allow delete and update on therapist storage" on storage.objects;
create policy "Allow delete and update on therapist storage" on storage.objects for all using (bucket_id in ('brand-assets', 'therapist-photos', 'therapist-documents'));

-- 4. Tabel Customers (Data Pelanggan)
create table if not exists customers (
    id bigint generated by default as identity primary key,
    full_name text not null,
    phone text not null,
    email text,
    address text not null,
    city_area text,
    manual_orders_count integer default 0, -- Riwayat order manual / offline sebelum sistem dibuat
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MIGRATION HELPER CUSTOMERS:
-- alter table customers add column if not exists manual_orders_count integer default 0;

-- 5. Tabel Bookings (Pemesanan Layanan Home Massage)
create table if not exists bookings (
    id bigint generated by default as identity primary key,
    customer_id bigint references customers(id) on delete cascade,
    service_id bigint references services(id) on delete set null,
    therapist_id bigint references therapists(id) on delete set null,
    booking_date date not null default current_date,
    booking_time text not null default '10:00',
    service_address text not null,
    total_price numeric not null default 150000,
    status text default 'pending', -- 'pending', 'confirmed', 'on_the_way', 'in_progress', 'completed', 'cancelled'
    payment_method text default 'cash', -- 'cash', 'bank_transfer', 'qris', 'credit_card'
    payment_status text default 'unpaid', -- 'unpaid', 'paid', 'refunded'
    special_requests text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Tabel Invoices (Nota & Checkout Pembayaran)
create table if not exists invoices (
    id bigint generated by default as identity primary key,
    invoice_number text unique not null,
    public_token text unique, -- Token akses unik Midtrans/Stripe style untuk link publik (contoh: inv_k8X9pL2vM4qR1zW7)
    booking_id bigint references bookings(id) on delete set null,
    customer_id bigint references customers(id) on delete set null,
    customer_name text not null,
    customer_phone text not null,
    service_id bigint references services(id) on delete set null,
    service_name text not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name text,
    booking_date date,
    booking_time text,
    service_address text,
    subtotal numeric not null default 0,
    discount numeric default 0,
    transport_fee numeric default 0,
    additional_charge numeric default 0,
    additional_charge_description text,
    total_amount numeric not null default 0,
    payment_method text default 'cash', -- 'cash', 'qris', 'bank_transfer'
    payment_status text default 'unpaid', -- 'unpaid', 'paid', 'refunded'
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MIGRATION HELPER INVOICES:
-- alter table invoices add column if not exists public_token text unique;

-- 6b. Tabel Relasional 3NF: booking_items & invoice_items
create table if not exists booking_items (
    id bigint generated by default as identity primary key,
    booking_id bigint references bookings(id) on delete cascade,
    service_id bigint references services(id) on delete set null,
    service_name_snapshot text not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name_snapshot text,
    price numeric not null default 0,
    commission_rate_snapshot numeric not null default 60,
    consumables_cost_snapshot numeric not null default 0,
    duration_minutes_snapshot integer default 60,
    transport_fee numeric default 0,
    additional_charge numeric default 0,
    additional_charge_description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists invoice_items (
    id bigint generated by default as identity primary key,
    invoice_id bigint references invoices(id) on delete cascade,
    service_id bigint references services(id) on delete set null,
    service_name_snapshot text not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name_snapshot text,
    price numeric not null default 0,
    commission_rate_snapshot numeric not null default 60,
    consumables_cost_snapshot numeric not null default 0,
    therapist_fee_calculated numeric not null default 0,
    transport_fee numeric default 0,
    additional_charge numeric default 0,
    additional_charge_description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Tabel Reviews (Ulasan & Rating Pelanggan)
create table if not exists reviews (
    id bigint generated by default as identity primary key,
    booking_id bigint references bookings(id) on delete cascade,
    invoice_id bigint references invoices(id) on delete set null,
    therapist_id bigint references therapists(id) on delete set null,
    customer_name text,
    rating integer not null check (rating >= 1 and rating <= 5),
    comment text,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Tabel Brand Settings (Pengaturan Brand & Kontak Global)
create table if not exists brand_settings (
    id integer primary key default 1 check (id = 1),
    brand_name text not null default 'Serena Raga',
    tagline text default 'Comfortable Home Massage & Spa',
    description text default 'Layanan terapis pijat dan spa profesional langsung ke rumah, hotel, dan apartemen Anda.',
    whatsapp_number text not null default '6281234567890',
    phone_number text default '+62 812-3456-7890',
    email text default 'support@serenaraga.com',
    website_url text default 'https://serenaraga.com',
    instagram_handle text default '@serenaraga',
    operational_hours text default '08:00 - 22:00 WIB (Setiap Hari)',
    service_areas text default 'Jakarta, Tangerang, Depok, Bekasi, & Sekitarnya',
    bank_name text default 'BCA (Bank Central Asia)',
    bank_account_number text default '8720-1928-33',
    bank_account_holder text default 'PT Serena Raga Indonesia',
    qris_image_url text default '',
    invoice_footer_note text default 'Terima kasih telah mempercayakan relaksasi Anda pada Serena Raga.',
    invoice_support_text text default 'Dokumen ini merupakan bukti transaksi resmi. Layanan pelanggan WhatsApp {whatsapp}.',
    wa_invoice_message_template text default 'Halo {customer_name},\n\nTerima kasih telah menggunakan layanan *{brand_name}* ({service_name}).\nBerikut adalah rincian nota & invoice resmi Anda:\n\n📄 *No. Invoice:* {invoice_number}\n💰 *Total Tagihan:* {total_amount}\n📅 *Jadwal:* {booking_date} jam {booking_time}\n💳 *Status:* {payment_status}\n\n🔗 *Lihat Nota Digital:* {invoice_url}\n\nJika ada pertanyaan, silakan hubungi kami via WhatsApp ini.',
    wa_booking_message_template text default 'Halo {customer_name},\n\nPesanan *{service_name}* di *{brand_name}* Anda telah dikonfirmasi!\n\n📅 *Tanggal:* {booking_date}\n⏰ *Jam:* {booking_time}\n📍 *Alamat:* {address}\n💆 *Terapis:* {therapist_name}\n\nMohon bersiap 10 menit sebelum waktu pelayanan.',
    wa_support_default_message text default 'Halo Customer Service {brand_name}, saya butuh bantuan mengenai layanan / nota saya.',
    facebook_url text default 'https://facebook.com/serenaraga',
    threads_handle text default '@serenaraga',
    tiktok_handle text default '@serenaraga',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Migration helper if brand_settings table already exists
alter table brand_settings add column if not exists facebook_url text default 'https://facebook.com/serenaraga';
alter table brand_settings add column if not exists threads_handle text default '@serenaraga';
alter table brand_settings add column if not exists tiktok_handle text default '@serenaraga';
alter table brand_settings add column if not exists qris_payload text default '';

-- Seed default brand settings if empty
insert into brand_settings (id, brand_name, whatsapp_number)
values (1, 'Serena Raga', '6281234567890')
on conflict (id) do nothing;

-- 9. Tabel App Users (Manajemen Pengguna & Hak Akses Admin / Kasir)
create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    email text,
    full_name text not null,
    password_hash text not null,
    role text not null default 'cashier' check (role in ('admin', 'cashier', 'manager')),
    phone text,
    avatar_url text,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pastikan semua kolom baru tersedia jika tabel sudah terlanjur dibuat sebelumnya
alter table app_users add column if not exists email text;
alter table app_users add column if not exists phone text;
alter table app_users add column if not exists avatar_url text;
alter table app_users add column if not exists is_active boolean default true;

-- Seed default Super Admin user if not exists
insert into app_users (username, email, full_name, password_hash, role)
values 
    ('admin@serenaraga', 'admin@serenaraga.com', 'Owner / Super Admin', 'Adminserena2026', 'admin'),
    ('admin@serenaraga.com', 'admin@serenaraga.com', 'Owner / Super Admin', 'Adminserena2026', 'admin')
on conflict (username) do update
set 
    password_hash = excluded.password_hash,
    role = 'admin',
    is_active = true;

-- 10. Enable Row Level Security (RLS)
alter table services enable row level security;
alter table therapists enable row level security;
alter table customers enable row level security;
alter table bookings enable row level security;
alter table reviews enable row level security;
alter table invoices enable row level security;
alter table brand_settings enable row level security;
alter table app_users enable row level security;

-- 11. Re-create Public Policies Safely (Drop if exists then create)
drop policy if exists "Allow anon full access on services" on services;
create policy "Allow anon full access on services" on services for all using (true) with check (true);

drop policy if exists "Allow anon full access on therapists" on therapists;
create policy "Allow anon full access on therapists" on therapists for all using (true) with check (true);

drop policy if exists "Allow anon full access on customers" on customers;
create policy "Allow anon full access on customers" on customers for all using (true) with check (true);

drop policy if exists "Allow anon full access on bookings" on bookings;
create policy "Allow anon full access on bookings" on bookings for all using (true) with check (true);

drop policy if exists "Allow anon full access on reviews" on reviews;
create policy "Allow anon full access on reviews" on reviews for all using (true) with check (true);

drop policy if exists "Allow anon full access on invoices" on invoices;
create policy "Allow anon full access on invoices" on invoices for all using (true) with check (true);

drop policy if exists "Allow anon full access on brand_settings" on brand_settings;
create policy "Allow anon full access on brand_settings" on brand_settings for all using (true) with check (true);

drop policy if exists "Allow anon full access on app_users" on app_users;
create policy "Allow anon full access on app_users" on app_users for all using (true) with check (true);

-- 12. Create Indexes for Performance
create index if not exists idx_bookings_customer on bookings(customer_id);
create index if not exists idx_bookings_service on bookings(service_id);
create index if not exists idx_bookings_therapist on bookings(therapist_id);
create index if not exists idx_bookings_date on bookings(booking_date);
create index if not exists idx_therapists_status on therapists(status);
create index if not exists idx_invoices_number on invoices(invoice_number);
create index if not exists idx_invoices_booking on invoices(booking_id);
create index if not exists idx_app_users_username on app_users(username);
create index if not exists idx_app_users_role on app_users(role);

-- 13. Storage Buckets & Policies for Therapist Photos & Documents
-- Membuat storage bucket otomatis jika belum ada
insert into storage.buckets (id, name, public)
values 
    ('therapist-photos', 'therapist-photos', true),
    ('therapist-documents', 'therapist-documents', true)
on conflict (id) do update set public = true;

-- Policy agar upload foto & dokumen terapis diizinkan tanpa error RLS
drop policy if exists "Public Access for Therapist Storage" on storage.objects;
create policy "Public Access for Therapist Storage"
on storage.objects for all
using (bucket_id in ('therapist-photos', 'therapist-documents'))
with check (bucket_id in ('therapist-photos', 'therapist-documents'));

-- 14. Tabel Therapist Payouts (Rekap Bagi Hasil & Slip Pembayaran Terapis)
create table if not exists therapist_payouts (
    id bigint generated by default as identity primary key,
    payout_number text unique not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name text not null,
    period_type text default 'monthly', -- 'daily', 'weekly', 'monthly', 'custom'
    period_start date not null,
    period_end date not null,
    total_bookings integer not null default 0,
    gross_amount numeric not null default 0,
    commission_rate numeric not null default 60,
    therapist_fee numeric not null default 0,
    company_fee numeric not null default 0,
    bonus_amount numeric default 0,
    deduction_amount numeric default 0,
    net_amount numeric not null default 0,
    bank_name text default 'BCA',
    bank_account_number text,
    bank_account_name text,
    payment_status text default 'paid', -- 'pending', 'paid'
    payment_date date default current_date,
    notes text,
    bookings_breakdown jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure bookings_breakdown exists on therapist_payouts if table already created
alter table therapist_payouts add column if not exists bookings_breakdown jsonb;

alter table therapist_payouts enable row level security;
drop policy if exists "Allow anon full access on therapist_payouts" on therapist_payouts;
create policy "Allow anon full access on therapist_payouts" on therapist_payouts for all using (true) with check (true);

create index if not exists idx_payouts_therapist on therapist_payouts(therapist_id);
create index if not exists idx_payouts_number on therapist_payouts(payout_number);
create index if not exists idx_payouts_period on therapist_payouts(period_start, period_end);

-- 15. Tabel Consumables (Master Bahan Habis Pakai / HPP Operasional)
create table if not exists consumables (
    id bigint generated by default as identity primary key,
    name text not null,
    category text default 'Oil & Lotion', -- 'Oil & Lotion', 'Scrub & Lulur', 'Essential Oil', 'Spa Supplies', 'Linen & Hygiene'
    unit text not null default 'ml', -- 'ml', 'gram', 'pcs', 'set', 'tetes'
    cost_per_unit numeric not null default 0, -- Harga pokok per satuan (misal Rp 150 / ml)
    stock_quantity numeric default 0, -- Estimasi persediaan stok
    min_stock_alert numeric default 100, -- Batas minimal peringatan restock
    is_active boolean default true,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 16. Tabel Service Consumables (Takaran Bahan yang Digunakan per Layanan)
create table if not exists service_consumables (
    id bigint generated by default as identity primary key,
    service_id bigint references services(id) on delete cascade,
    consumable_id bigint references consumables(id) on delete cascade,
    quantity numeric not null default 1, -- Takaran pemakaian (misal: 50 ml)
    unit_cost_snapshot numeric default 0, -- Snapshot harga unit saat dipasang
    total_cost numeric not null default 0, -- quantity * unit_cost
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tambah kolom consumables_cost pada services jika belum ada
alter table services add column if not exists consumables_cost numeric default 0;

-- Enable RLS and Policies for Consumables
alter table consumables enable row level security;
drop policy if exists "Allow anon full access on consumables" on consumables;
create policy "Allow anon full access on consumables" on consumables for all using (true) with check (true);

alter table service_consumables enable row level security;
drop policy if exists "Allow anon full access on service_consumables" on service_consumables;
create policy "Allow anon full access on service_consumables" on service_consumables for all using (true) with check (true);

-- Indexes for Consumables
create index if not exists idx_consumables_category on consumables(category);
create index if not exists idx_service_consumables_service on service_consumables(service_id);
create index if not exists idx_service_consumables_consumable on service_consumables(consumable_id);

-- 17. Tabel Testimonials (Testimoni Screenshot WhatsApp Asli Pelanggan)
create table if not exists testimonials (
    id bigint generated by default as identity primary key,
    customer_name text default 'Pelanggan Serena Raga',
    service_name text default 'Traditional Massage',
    image_url text not null, -- URL Screenshot Chat WhatsApp di Supabase Storage
    caption text, -- Ringkasan / Kutipan Review Chat
    rating integer default 5 check (rating >= 1 and rating <= 5),
    is_active boolean default true, -- Ditampilkan di Landing Page
    sort_order integer default 0, -- Urutan tampil (0 = otomatis urut ID)
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Testimonials
alter table testimonials enable row level security;
drop policy if exists "Allow anon full access on testimonials" on testimonials;
create policy "Allow anon full access on testimonials" on testimonials for all using (true) with check (true);

create index if not exists idx_testimonials_active on testimonials(is_active, sort_order);

-- Setup Supabase Storage Bucket untuk Testimonials Screenshot
insert into storage.buckets (id, name, public)
values ('testimonials', 'testimonials', true)
on conflict (id) do update set public = true;

drop policy if exists "Allow public read on testimonials storage" on storage.objects;
create policy "Allow public read on testimonials storage" on storage.objects for select using (bucket_id = 'testimonials');

drop policy if exists "Allow authenticated and anon uploads to testimonials storage" on storage.objects;
create policy "Allow authenticated and anon uploads to testimonials storage" on storage.objects for insert with check (bucket_id = 'testimonials');

drop policy if exists "Allow delete and update on testimonials storage" on storage.objects;
create policy "Allow delete and update on testimonials storage" on storage.objects for all using (bucket_id = 'testimonials');

-- 18. Tabel Promotions (Manajemen Diskon, Voucher & Promo Otomatis)
create table if not exists promotions (
    id bigint generated by default as identity primary key,
    name text not null,
    code text,
    type text not null default 'percentage', -- 'percentage', 'fixed'
    value numeric not null default 5, -- misal 5 (%) atau 20000 (IDR)
    scope text not null default 'first_order', -- 'first_order', 'loyalty_milestone', 'all', 'min_order', 'code'
    min_orders_count integer default 0, -- Syarat minimum order selesai untuk loyalitas (misal: 10x)
    min_order_amount numeric not null default 0,
    max_discount_cap numeric,
    deduct_from_therapist_commission boolean default false, -- False = Serena Raga menanggung beban diskon
    allow_stacking boolean default false,
    is_active boolean default true,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS and Policies for Promotions
alter table promotions enable row level security;
drop policy if exists "Allow anon full access on promotions" on promotions;
create policy "Allow anon full access on promotions" on promotions for all using (true) with check (true);

-- Indexes for Promotions
create index if not exists idx_promotions_active on promotions(is_active, scope);
create index if not exists idx_promotions_code on promotions(code);

-- Seed Data Promo Default (Diskon Pelanggan Baru 5%, Loyalitas 10%, Weekend)
insert into promotions (name, code, type, value, scope, min_orders_count, min_order_amount, deduct_from_therapist_commission, is_active, description)
values 
    ('Diskon 5% Pelanggan Baru', 'FIRST5', 'percentage', 5, 'first_order', 0, 0, false, true, 'Otomatis aktif untuk pelanggan yang pertama kali memesan di Serena Raga.'),
    ('Promo Loyalitas 10x Order (10% OFF)', 'LOYAL10', 'percentage', 10, 'loyalty_milestone', 10, 0, false, true, 'Diskon 10% apresiasi pelanggan setia yang telah mencapai 10x pemesanan.'),
    ('Promo Weekend Relaksasi', 'WEEKEND10', 'percentage', 10, 'min_order', 0, 250000, false, true, 'Diskon 10% untuk pemesanan di atas Rp 250.000.'),
    ('Voucher Loyalitas Serena VIP', 'SERENAVIP', 'fixed', 25000, 'code', 0, 150000, false, true, 'Potongan langsung Rp 25.000 dengan kode voucher.')
on conflict do nothing;

-- =========================================================
-- 19. TABEL RELASIONAL 3NF: BOOKING ITEMS
-- Menyimpan rincian setiap baris layanan & penugasan terapis per booking
-- =========================================================
create table if not exists booking_items (
    id bigint generated by default as identity primary key,
    booking_id bigint references bookings(id) on delete cascade,
    service_id bigint references services(id) on delete set null,
    service_name_snapshot text not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name_snapshot text,
    price numeric not null default 0,
    commission_rate_snapshot numeric not null default 60,
    consumables_cost_snapshot numeric not null default 0,
    duration_minutes_snapshot integer not null default 60,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_booking_items_booking on booking_items(booking_id);
create index if not exists idx_booking_items_service on booking_items(service_id);
create index if not exists idx_booking_items_therapist on booking_items(therapist_id);

alter table booking_items enable row level security;
drop policy if exists "Allow anon full access on booking_items" on booking_items;
create policy "Allow anon full access on booking_items" on booking_items for all using (true) with check (true);

-- =========================================================
-- 20. TABEL RELASIONAL 3NF: INVOICE ITEMS
-- Menyimpan rincian baris tagihan checkout POS & kalkulasi fee terapis
-- =========================================================
create table if not exists invoice_items (
    id bigint generated by default as identity primary key,
    invoice_id bigint references invoices(id) on delete cascade,
    booking_item_id bigint references booking_items(id) on delete set null,
    service_id bigint references services(id) on delete set null,
    service_name_snapshot text not null,
    therapist_id bigint references therapists(id) on delete set null,
    therapist_name_snapshot text,
    price numeric not null default 0,
    commission_rate_snapshot numeric not null default 60,
    consumables_cost_snapshot numeric not null default 0,
    therapist_fee_calculated numeric not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_invoice_items_invoice on invoice_items(invoice_id);
create index if not exists idx_invoice_items_service on invoice_items(service_id);
create index if not exists idx_invoice_items_therapist on invoice_items(therapist_id);

alter table invoice_items enable row level security;
drop policy if exists "Allow anon full access on invoice_items" on invoice_items;
create policy "Allow anon full access on invoice_items" on invoice_items for all using (true) with check (true);

-- =========================================================
-- 21. POSTGRESQL STORED PROCEDURES (RPC) UNTUK TRANSAKSI ATOMIK
-- =========================================================

-- A. RPC: Atomic Create Complete Booking
create or replace function rpc_create_booking_atomic(
    p_customer jsonb,
    p_booking jsonb,
    p_items jsonb
) returns jsonb as $$
declare
    v_customer_id bigint;
    v_booking_id bigint;
    v_item jsonb;
    v_total_price numeric := 0;
    v_first_service_id bigint := null;
    v_first_therapist_id bigint := null;
begin
    -- 1. Resolve or Create Customer by Phone
    if (p_customer->>'id') is not null and (p_customer->>'id') != '' and (p_customer->>'id') != 'null' then
        v_customer_id := (p_customer->>'id')::bigint;
    else
        select id into v_customer_id from customers 
        where right(regexp_replace(phone, '\D', '', 'g'), 8) = right(regexp_replace(p_customer->>'phone', '\D', '', 'g'), 8)
        limit 1;

        if v_customer_id is null then
            insert into customers (full_name, phone, address, notes)
            values (
                coalesce(p_customer->>'full_name', 'Pelanggan'),
                coalesce(p_customer->>'phone', '-'),
                coalesce(p_customer->>'address', coalesce(p_booking->>'service_address', '-')),
                p_customer->>'notes'
            ) returning id into v_customer_id;
        else
            update customers set
                full_name = coalesce(p_customer->>'full_name', full_name),
                address = coalesce(p_booking->>'service_address', address)
            where id = v_customer_id;
        end if;
    end if;

    -- 2. Compute summary values from items array
    if jsonb_array_length(p_items) > 0 then
        v_first_service_id := (p_items->0->>'service_id')::bigint;
        v_first_therapist_id := (p_items->0->>'therapist_id')::bigint;
        
        for v_item in select * from jsonb_array_elements(p_items)
        loop
            v_total_price := v_total_price + coalesce((v_item->>'price')::numeric, 0);
        end loop;
    else
        v_total_price := coalesce((p_booking->>'total_price')::numeric, 0);
    end if;

    -- 3. Insert Master Booking
    insert into bookings (
        customer_id,
        service_id,
        therapist_id,
        booking_date,
        booking_time,
        service_address,
        total_price,
        status,
        payment_method,
        payment_status,
        special_requests
    ) values (
        v_customer_id,
        v_first_service_id,
        v_first_therapist_id,
        coalesce((p_booking->>'booking_date')::date, current_date),
        coalesce(p_booking->>'booking_time', '10:00'),
        coalesce(p_booking->>'service_address', '-'),
        v_total_price,
        coalesce(p_booking->>'status', 'pending'),
        coalesce(p_booking->>'payment_method', 'cash'),
        coalesce(p_booking->>'payment_status', 'unpaid'),
        p_booking->>'special_requests'
    ) returning id into v_booking_id;

    -- 4. Batch Insert Relational Booking Items
    for v_item in select * from jsonb_array_elements(p_items)
    loop
        insert into booking_items (
            booking_id,
            service_id,
            service_name_snapshot,
            therapist_id,
            therapist_name_snapshot,
            price,
            commission_rate_snapshot,
            consumables_cost_snapshot,
            duration_minutes_snapshot
        ) values (
            v_booking_id,
            (v_item->>'service_id')::bigint,
            coalesce(v_item->>'service_name', 'Layanan'),
            (v_item->>'therapist_id')::bigint,
            v_item->>'therapist_name',
            coalesce((v_item->>'price')::numeric, 0),
            coalesce((v_item->>'rate')::numeric, 60),
            coalesce((v_item->>'bhp')::numeric, 0),
            coalesce((v_item->>'duration_minutes')::integer, 60)
        );
    end loop;

    return jsonb_build_object(
        'success', true,
        'booking_id', v_booking_id,
        'customer_id', v_customer_id,
        'total_price', v_total_price
    );
end;
$$ language plpgsql security definer;

-- B. RPC: Atomic Create Complete Invoice
create or replace function rpc_create_invoice_atomic(
    p_invoice jsonb,
    p_items jsonb
) returns jsonb as $$
declare
    v_invoice_id bigint;
    v_item jsonb;
    v_invoice_number text;
begin
    v_invoice_number := coalesce(p_invoice->>'invoice_number', 'INV-' || to_char(now(), 'YYYYMMDD-HH24MISS'));

    -- 1. Insert Master Invoice
    insert into invoices (
        invoice_number,
        booking_id,
        customer_id,
        customer_name,
        customer_phone,
        service_id,
        service_name,
        therapist_id,
        therapist_name,
        booking_date,
        booking_time,
        service_address,
        subtotal,
        discount,
        transport_fee,
        total_amount,
        payment_method,
        payment_status,
        notes
    ) values (
        v_invoice_number,
        (p_invoice->>'booking_id')::bigint,
        (p_invoice->>'customer_id')::bigint,
        coalesce(p_invoice->>'customer_name', 'Pelanggan'),
        coalesce(p_invoice->>'customer_phone', '-'),
        (p_invoice->>'service_id')::bigint,
        coalesce(p_invoice->>'service_name', 'Layanan'),
        (p_invoice->>'therapist_id')::bigint,
        p_invoice->>'therapist_name',
        (p_invoice->>'booking_date')::date,
        p_invoice->>'booking_time',
        p_invoice->>'service_address',
        coalesce((p_invoice->>'subtotal')::numeric, 0),
        coalesce((p_invoice->>'discount')::numeric, 0),
        coalesce((p_invoice->>'transport_fee')::numeric, 0),
        coalesce((p_invoice->>'total_amount')::numeric, 0),
        coalesce(p_invoice->>'payment_method', 'cash'),
        coalesce(p_invoice->>'payment_status', 'unpaid'),
        p_invoice->>'notes'
    ) returning id into v_invoice_id;

    -- 2. Insert Line Items
    if p_items is not null and jsonb_array_length(p_items) > 0 then
        for v_item in select * from jsonb_array_elements(p_items)
        loop
            insert into invoice_items (
                invoice_id,
                service_id,
                service_name_snapshot,
                therapist_id,
                therapist_name_snapshot,
                price,
                commission_rate_snapshot,
                consumables_cost_snapshot,
                therapist_fee_calculated
            ) values (
                v_invoice_id,
                (v_item->>'service_id')::bigint,
                coalesce(v_item->>'service_name', coalesce(v_item->>'name', 'Layanan')),
                (v_item->>'therapist_id')::bigint,
                coalesce(v_item->>'therapist_name', v_item->>'therapist'),
                coalesce((v_item->>'price')::numeric, 0),
                coalesce((v_item->>'rate')::numeric, 60),
                coalesce((v_item->>'bhp')::numeric, 0),
                coalesce((v_item->>'commission')::numeric, 0)
            );
        end loop;
    end if;

    -- 3. Update Booking payment status if booking_id exists
    if (p_invoice->>'booking_id') is not null and (p_invoice->>'booking_id') != '' and (p_invoice->>'booking_id') != 'none' then
        update bookings set
            payment_status = coalesce(p_invoice->>'payment_status', payment_status),
            status = coalesce(p_invoice->>'booking_status', case when (p_invoice->>'payment_status') = 'paid' then 'completed' else status end)
        where id = (p_invoice->>'booking_id')::bigint;
    end if;

    return jsonb_build_object(
        'success', true,
        'invoice_id', v_invoice_id,
        'invoice_number', v_invoice_number
    );
end;
$$ language plpgsql security definer;

-- C. RPC: Ultra Fast Dashboard Analytics
create or replace function rpc_get_dashboard_analytics(
    p_start_date date default (current_date - interval '30 days')::date,
    p_end_date date default current_date
) returns jsonb as $$
declare
    v_total_revenue numeric := 0;
    v_paid_invoices integer := 0;
    v_total_bookings integer := 0;
    v_completed_bookings integer := 0;
    v_top_services jsonb;
    v_top_therapists jsonb;
begin
    -- 1. Revenue and Invoice metrics
    select 
        coalesce(sum(total_amount), 0),
        count(id)
    into v_total_revenue, v_paid_invoices
    from invoices
    where payment_status = 'paid'
      and (booking_date between p_start_date and p_end_date or (booking_date is null and created_at::date between p_start_date and p_end_date));

    -- 2. Bookings metrics
    select 
        count(id),
        count(id) filter (where status in ('completed', 'confirmed'))
    into v_total_bookings, v_completed_bookings
    from bookings
    where booking_date between p_start_date and p_end_date;

    -- 3. Top Services by volume
    select jsonb_agg(sub) into v_top_services from (
        select service_name as name, count(*) as count, sum(total_amount) as revenue
        from invoices
        where payment_status = 'paid'
          and (booking_date between p_start_date and p_end_date or (booking_date is null and created_at::date between p_start_date and p_end_date))
        group by service_name
        order by count desc
        limit 5
    ) sub;

    -- 4. Top Therapists by volume
    select jsonb_agg(sub) into v_top_therapists from (
        select therapist_name as name, count(*) as count, sum(total_amount) as revenue
        from invoices
        where payment_status = 'paid'
          and therapist_name is not null
          and (booking_date between p_start_date and p_end_date or (booking_date is null and created_at::date between p_start_date and p_end_date))
        group by therapist_name
        order by count desc
        limit 5
    ) sub;

    return jsonb_build_object(
        'total_revenue', v_total_revenue,
        'paid_invoices', v_paid_invoices,
        'total_bookings', v_total_bookings,
        'completed_bookings', v_completed_bookings,
        'top_services', coalesce(v_top_services, '[]'::jsonb),
        'top_therapists', coalesce(v_top_therapists, '[]'::jsonb)
    );
end;
$$ language plpgsql security definer;

-- ==============================================================================
-- PERFORMANCE INDEXES (High-Speed Pagination, Filtering & Relational Lookups)
-- ==============================================================================

-- Bookings indexes (Optimizes React-Admin list sorting & relations)
create index if not exists idx_bookings_id_desc on bookings(id desc);
create index if not exists idx_bookings_date_id on bookings(booking_date desc, id desc);
create index if not exists idx_bookings_customer_id on bookings(customer_id);
create index if not exists idx_bookings_service_id on bookings(service_id);
create index if not exists idx_bookings_therapist_id on bookings(therapist_id);
create index if not exists idx_bookings_status on bookings(status);
create index if not exists idx_bookings_payment_status on bookings(payment_status);

-- Invoices indexes (Optimizes POS, invoice list, and reporting)
create index if not exists idx_invoices_id_desc on invoices(id desc);
create index if not exists idx_invoices_created_at on invoices(created_at desc);
create index if not exists idx_invoices_booking_id on invoices(booking_id);
create index if not exists idx_invoices_customer_id on invoices(customer_id);
create index if not exists idx_invoices_therapist_id on invoices(therapist_id);
create index if not exists idx_invoices_payment_status on invoices(payment_status);
create index if not exists idx_invoices_customer_phone on invoices(customer_phone);
create index if not exists idx_invoices_invoice_number on invoices(invoice_number);

-- Relational Line Items indexes
create index if not exists idx_booking_items_booking_id on booking_items(booking_id);
create index if not exists idx_invoice_items_invoice_id on invoice_items(invoice_id);

-- Customers indexes (Fast search & phone lookup)
create index if not exists idx_customers_phone on customers(phone);
create index if not exists idx_customers_full_name on customers(full_name);

-- Therapists & Services active status indexes
create index if not exists idx_therapists_status_idx on therapists(status);
create index if not exists idx_services_active on services(is_active);

-- ==============================================================================
-- REVIEWS TABLE (Customer Ratings & Reviews)
-- ==============================================================================
create table if not exists reviews (
    id bigint generated by default as identity primary key,
    booking_id bigint references bookings(id) on delete set null,
    invoice_id bigint references invoices(id) on delete set null,
    therapist_id bigint references therapists(id) on delete set null,
    customer_name text,
    rating integer not null default 5,
    comment text,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_reviews_booking_id on reviews(booking_id);
create index if not exists idx_reviews_therapist_id on reviews(therapist_id);
create index if not exists idx_reviews_invoice_id on reviews(invoice_id);
create index if not exists idx_reviews_created_at on reviews(created_at desc);

-- ==============================================================================
-- DATABASE MIGRATION SCRIPT (Run this in Supabase SQL Editor to apply new columns)
-- ==============================================================================
-- 1. Brand Settings (Dynamic QRIS Payload Storage)
alter table brand_settings add column if not exists qris_payload text default '';

-- 2. Reviews Columns (Extended Metadata & Relational Links)
alter table reviews add column if not exists customer_name text;
alter table reviews add column if not exists invoice_id bigint;
alter table reviews add column if not exists therapist_id bigint;
alter table reviews add column if not exists is_read boolean default false;



